// ==============================================================================
// Sculra Autonomous Safe Fix Agent Type Definitions (worker/src/fix-agent/types.ts)
// ==============================================================================

import { RemediationAnalysis, BugDiagnosis, FixPlan, VerificationPlan, RootCauseHypothesis } from '../remediation/types';
import { BugObservation } from '../issues/types';

/**
 * Execution modes supported by the Fix Agent.
 * Default is PLAN_ONLY.
 */
export type FixAgentMode = 'PLAN_ONLY' | 'DRY_RUN' | 'APPLY_AND_VERIFY' | 'CREATE_PR';

/**
 * Formal 18-state state machine for the Fix Agent remediation lifecycle.
 */
export type FixAgentState =
  | 'REQUESTED'
  | 'AUTHORIZED'
  | 'DIAGNOSIS_VALIDATED'
  | 'CONTEXT_COLLECTED'
  | 'PATCH_GENERATED'
  | 'PATCH_VALIDATED'
  | 'WORKSPACE_CREATED'
  | 'BASELINE_VERIFIED'
  | 'PATCH_APPLIED'
  | 'DIFF_REVIEWED'
  | 'VERIFICATION_RUNNING'
  | 'VERIFIED'
  | 'FAILED'
  | 'ROLLED_BACK'
  | 'BRANCH_CREATED'
  | 'PR_CREATED'
  | 'CANCELLED'
  | 'BLOCKED';

/**
 * Baseline reproduction outcomes before patch application.
 */
export type FixBaselineStatus =
  | 'BASELINE_REPRODUCED'
  | 'BASELINE_NOT_REPRODUCED'
  | 'BASELINE_INCONCLUSIVE'
  | 'SKIPPED';
export type BaselineStatus = FixBaselineStatus;

/**
 * Post-patch verification outcomes.
 */
export type FixVerificationStatus =
  | 'VERIFIED_FIXED'
  | 'VERIFIED_NOT_FIXED'
  | 'PARTIALLY_VERIFIED'
  | 'VERIFICATION_FAILED'
  | 'VERIFICATION_TIMEOUT'
  | 'INCONCLUSIVE'
  | 'BLOCKED'
  | 'CANCELLED';
export type VerificationStatus = FixVerificationStatus;

/**
 * Types of immutable remediation evidence records.
 */
export type FixEvidenceType =
  | 'baseline_reproduction'
  | 'patch_generated'
  | 'patch_applied'
  | 'diff_review'
  | 'test_result'
  | 'verification_result'
  | 'rollback'
  | 'pr_created'
  | 'policy_blocked'
  | 'audit_event';

/**
 * Project-level remediation policy configuration.
 */
export interface ProjectFixPolicy {
  fix_agent_enabled: boolean;
  fix_agent_mode: FixAgentMode;
  fix_agent_allowed_branches: string[];
  fix_agent_max_files: number;
  fix_agent_max_diff_lines: number;
  fix_agent_max_test_commands: number;
  fix_agent_allow_dependency_changes: boolean;
  fix_agent_allow_config_changes: boolean;
  fix_agent_allow_database_changes: boolean;
  fix_agent_allow_auth_changes: boolean;
  fix_agent_allow_security_sensitive_changes: boolean;
  fix_agent_require_pr: boolean;
  fix_agent_auto_verify: boolean;
  fix_agent_allowed_paths: string[];
  fix_agent_blocked_paths: string[];
}

/**
 * Strongly typed FixRequest.
 */
export interface FixRequest {
  id?: string;
  projectId: string;
  organizationId?: string;
  issueId: string;
  testRunId?: string;
  campaignId?: string;
  diagnosisId?: string;
  fixPlanId?: string;
  repoOwner?: string;
  repoName?: string;
  sourceCommitSha: string;
  targetBranch: string;
  requestedMode: FixAgentMode;
  requesterUserId: string;
  userRoles?: string[];
  remediationAnalysis?: RemediationAnalysis;
  observation?: BugObservation;
  metadata?: Record<string, any>;
}

/**
 * Single patch edit representing a grounded code change region.
 */
export interface PatchEdit {
  targetFile: string;
  action: 'UPDATE' | 'CREATE' | 'DELETE';
  originalContentSnippet?: string;
  replacementContentSnippet: string;
  startLine?: number;
  endLine?: number;
  expectedFileSha?: string;
  reason: string;
  affectedSymbols: string[];
}

/**
 * Structured patch proposal generated by AI or deterministic rule.
 */
export interface StructuredPatch {
  summary: string;
  rationale: string;
  edits: PatchEdit[];
  expectedBehavior: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'SECURITY_RISK';
  affectedFiles: string[];
  verificationRequirements: string[];
  isDeterministic: boolean;
}

/**
 * Deterministic patch safety validation result.
 */
export interface PatchValidationResult {
  valid: boolean;
  blockedReason?: string;
  securitySensitive: boolean;
  securityFlags: string[];
  filesCount: number;
  linesCount: number;
  warnings: string[];
}

/**
 * Independent diff reviewer result.
 */
export interface DiffReviewResult {
  passed: boolean;
  filesChanged: string[];
  additions: number;
  deletions: number;
  changedSymbols: string[];
  securityViolations: string[];
  obfuscationDetected: boolean;
  secretsDetected: boolean;
  unauthorizedUrls: string[];
  unauthorizedCommands: string[];
  rawDiff: string;
  summary: string;
}

/**
 * Test command plan.
 */
export interface TestCommandPlan {
  commands: string[];
  targetedDomains: string[];
  timeoutSeconds: number;
}

/**
 * Single test command execution result.
 */
export interface TestCommandResult {
  command: string;
  exitCode: number;
  durationMs: number;
  passed: boolean;
  stdoutSnippet: string;
  stderrSnippet: string;
  timedOut: boolean;
  testCount?: number;
  failedTests?: string[];
}

/**
 * Comprehensive verification result.
 */
export interface FixVerificationResult {
  status: VerificationStatus;
  baselineStatus: BaselineStatus;
  targetedCommandResults: TestCommandResult[];
  regressionCommandResults: TestCommandResult[];
  summary: string;
  durationMs: number;
  allPassed: boolean;
}
export type VerificationResult = FixVerificationResult;

/**
 * Pull request creation result.
 */
export interface PullRequestResult {
  prNumber: number;
  prUrl: string;
  branchName: string;
  headSha: string;
  title: string;
  body: string;
  createdAt: string;
}

/**
 * Master remediation record matching public.fix_remediations.
 */
export interface FixRemediationRecord {
  id: string;
  organizationId?: string;
  projectId: string;
  issueId: string;
  testRunId?: string;
  campaignId?: string;
  diagnosisId?: string;
  fixPlanId?: string;
  requesterUserId: string;
  sourceCommitSha: string;
  targetBranch: string;
  remediationBranch?: string;
  mode: FixAgentMode;
  status: FixAgentState;
  baselineStatus?: BaselineStatus;
  verificationStatus?: VerificationStatus;
  changedFiles: string[];
  changedLines: number;
  testCommands: string[];
  verificationSummary: Record<string, any>;
  diffSummary: Record<string, any>;
  patchData: Record<string, any>;
  errorCode?: string;
  errorMessage?: string;
  prNumber?: number;
  prUrl?: string;
  metadata: Record<string, any>;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
}

/**
 * Evidence record matching public.fix_evidence.
 */
export interface FixEvidenceRecord {
  id?: string;
  remediationId: string;
  type: FixEvidenceType;
  summary: string;
  metadata?: Record<string, any>;
  createdAt?: string;
}

/**
 * Structured telemetry for a remediation execution.
 */
export interface FixTelemetry {
  remediationId: string;
  projectId: string;
  issueId: string;
  mode: FixAgentMode;
  finalState: FixAgentState;
  totalDurationMs: number;
  aiLatencyMs?: number;
  aiModel?: string;
  tokensUsed?: number;
  patchAttempts: number;
  filesInspected: number;
  filesChanged: number;
  linesChanged: number;
  testCount: number;
  verificationDurationMs: number;
  prCreationDurationMs?: number;
}
