// ==============================================================================
// Sculra Deterministic Accessibility Severity & WCAG Classifier (worker/src/accessibility/severity.ts)
// ==============================================================================

import {
  AccessibilityFindingType,
  AccessibilitySeverity,
  AccessibilityConfidence,
  WcagPrinciple,
} from './types';

export interface FindingMetadata {
  title: string;
  wcagReference: string;
  principle: WcagPrinciple;
  defaultSeverity: AccessibilitySeverity;
  defaultConfidence: AccessibilityConfidence;
  remediationHint: string;
}

export class AccessibilitySeverityClassifier {
  private static readonly METADATA_MAP: Record<AccessibilityFindingType, FindingMetadata> = {
    KEYBOARD_TRAP: {
      title: 'Keyboard Focus Trap Detected',
      wcagReference: 'WCAG 2.1 AA 2.1.2 No Keyboard Trap',
      principle: 'Operable',
      defaultSeverity: 'critical',
      defaultConfidence: 'high',
      remediationHint: 'Ensure keyboard focus can navigate away from the region using standard Tab/Shift+Tab or Escape keys without getting locked in an infinite cycle.',
    },
    KEYBOARD_INACCESSIBLE: {
      title: 'Interactive Control Inaccessible by Keyboard',
      wcagReference: 'WCAG 2.1 AA 2.1.1 Keyboard',
      principle: 'Operable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Ensure all interactive controls are reachable and activatable using standard keyboard keys (Tab, Enter, Space).',
    },
    CONTENT_NOT_REACHABLE_BY_KEYBOARD: {
      title: 'Content Not Reachable by Keyboard Navigation',
      wcagReference: 'WCAG 2.1 AA 2.1.1 Keyboard',
      principle: 'Operable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Ensure interactive elements receive keyboard focus in logical order and are not excluded with negative tabindex.',
    },
    FOCUS_NOT_VISIBLE: {
      title: 'Focus Indicator Not Visible',
      wcagReference: 'WCAG 2.1 AA 2.4.7 Focus Visible',
      principle: 'Operable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Provide a clearly visible outline, border, or box-shadow when interactive elements receive keyboard focus (do not set outline: none without fallback).',
    },
    FOCUS_ORDER_ERROR: {
      title: 'Illogical Keyboard Focus Order',
      wcagReference: 'WCAG 2.1 AA 2.4.3 Focus Order',
      principle: 'Operable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Align DOM order with visual presentation so keyboard navigation follows a logical, predictable sequence.',
    },
    TAB_ORDER_ERROR: {
      title: 'Tab Order Misconfiguration',
      wcagReference: 'WCAG 2.1 AA 2.4.3 Focus Order',
      principle: 'Operable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Avoid positive tabindex values (tabindex > 0); use natural DOM source ordering.',
    },
    SKIP_NAVIGATION_FAILURE: {
      title: 'Skip Navigation Link Broken or Missing',
      wcagReference: 'WCAG 2.1 AA 2.4.1 Bypass Blocks',
      principle: 'Operable',
      defaultSeverity: 'low',
      defaultConfidence: 'medium',
      remediationHint: 'Provide a visible skip-to-content mechanism at the top of the page targeting the main content region.',
    },
    MISSING_ACCESSIBLE_NAME: {
      title: 'Interactive Element Missing Accessible Name',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Provide an accessible name using textContent, aria-label, or aria-labelledby.',
    },
    EMPTY_BUTTON_NAME: {
      title: 'Button Has No Accessible Name',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Add meaningful visible text, an aria-label, or an image alt text inside the button.',
    },
    EMPTY_LINK_NAME: {
      title: 'Link Has No Accessible Text',
      wcagReference: 'WCAG 2.1 AA 2.4.4 Link Purpose (In Context)',
      principle: 'Operable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Provide descriptive text for the link describing its destination or purpose.',
    },
    INPUT_MISSING_LABEL: {
      title: 'Form Input Missing Associated Label',
      wcagReference: 'WCAG 2.1 AA 3.3.2 Labels or Instructions',
      principle: 'Understandable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Associate a <label for="inputId"> with the input or supply aria-label/aria-labelledby.',
    },
    LABEL_NOT_ASSOCIATED: {
      title: 'Label Not Programmatically Associated with Input',
      wcagReference: 'WCAG 2.1 AA 1.3.1 Info and Relationships',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Set the label `for` attribute to match the input `id` or wrap the input inside the <label> element.',
    },
    INVALID_FORM_LABEL: {
      title: 'Invalid Form Labeling',
      wcagReference: 'WCAG 2.1 AA 3.3.2 Labels or Instructions',
      principle: 'Understandable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Ensure form labels contain non-empty, meaningful text describing the expected input.',
    },
    REQUIRED_FIELD_NOT_EXPOSED: {
      title: 'Required Form Field Not Programmatically Exposed',
      wcagReference: 'WCAG 2.1 AA 3.3.2 Labels or Instructions',
      principle: 'Understandable',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Add native `required` attribute or `aria-required="true"` to required form fields.',
    },
    FORM_ERROR_NOT_ACCESSIBLE: {
      title: 'Form Error Message Not Accessible',
      wcagReference: 'WCAG 2.1 AA 3.3.1 Error Identification',
      principle: 'Understandable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Link error messages to invalid form inputs using `aria-describedby` or `aria-errormessage`.',
    },
    ERROR_MESSAGE_NOT_ASSOCIATED: {
      title: 'Validation Error Not Programmatically Associated',
      wcagReference: 'WCAG 2.1 AA 3.3.1 Error Identification',
      principle: 'Understandable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Associate the error message container with the field via `aria-describedby="errorId"`.',
    },
    STATUS_MESSAGE_NOT_ACCESSIBLE: {
      title: 'Dynamic Status Message Not Announced',
      wcagReference: 'WCAG 2.1 AA 4.1.3 Status Messages',
      principle: 'Robust',
      defaultSeverity: 'low',
      defaultConfidence: 'medium',
      remediationHint: 'Use `role="status"` or `aria-live="polite"` on containers that receive dynamic status updates.',
    },
    INVALID_ARIA_USAGE: {
      title: 'Invalid WAI-ARIA Usage',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Adhere to standard WAI-ARIA authoring practices; prefer native HTML5 semantics.',
    },
    ARIA_ROLE_INVALID: {
      title: 'Invalid ARIA Role',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Use only valid roles from the W3C WAI-ARIA role registry.',
    },
    ARIA_ATTRIBUTE_INVALID: {
      title: 'Invalid or Unsupported ARIA Attribute',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Remove or correct misspelled or unsupported `aria-*` attributes.',
    },
    ARIA_HIDDEN_FOCUSABLE: {
      title: 'Focusable Element Has aria-hidden="true"',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Do not place `aria-hidden="true"` on elements that can receive keyboard focus; add `tabindex="-1"` if intentionally hidden.',
    },
    HIDDEN_CONTENT_FOCUSABLE: {
      title: 'Visually Hidden Element Receives Focus',
      wcagReference: 'WCAG 2.1 AA 2.4.3 Focus Order',
      principle: 'Operable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Remove offscreen or hidden elements from the tab order using `tabindex="-1"` or `display: none`.',
    },
    HEADING_HIERARCHY_ERROR: {
      title: 'Heading Hierarchy Skipped Levels',
      wcagReference: 'WCAG 2.1 AA 1.3.1 Info and Relationships',
      principle: 'Perceivable',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Nest headings sequentially (e.g. <h1> followed by <h2>) without skipping levels.',
    },
    MISSING_MAIN_LANDMARK: {
      title: 'Page Missing Main Landmark Region',
      wcagReference: 'WCAG 2.1 AA 1.3.1 Info and Relationships',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Wrap the primary content of the page in a `<main>` or `role="main"` landmark.',
    },
    DUPLICATE_MAIN_LANDMARK: {
      title: 'Duplicate Main Landmarks on Page',
      wcagReference: 'WCAG 2.1 AA 1.3.1 Info and Relationships',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Ensure there is only one `<main>` landmark per document, or provide unique `aria-label`s.',
    },
    LANDMARK_STRUCTURE_ERROR: {
      title: 'Landmark Structural Defect',
      wcagReference: 'WCAG 2.1 AA 1.3.1 Info and Relationships',
      principle: 'Perceivable',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Structure page sections with appropriate semantic HTML5 landmarks (<header>, <nav>, <main>, <footer>).',
    },
    DIALOG_ACCESSIBILITY_ERROR: {
      title: 'Dialog Accessibility Defect',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Provide `role="dialog"`, accessible name, and modal focus management for dialog overlays.',
    },
    DIALOG_MISSING_NAME: {
      title: 'Dialog Missing Accessible Title/Name',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Add `aria-labelledby` referencing the dialog heading, or provide `aria-label`.',
    },
    DIALOG_FOCUS_ERROR: {
      title: 'Dialog Focus Management Defect',
      wcagReference: 'WCAG 2.1 AA 2.4.3 Focus Order',
      principle: 'Operable',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Trap focus within open modal dialogs and restore focus to the trigger button upon closing.',
    },
    IMAGE_MISSING_ALT: {
      title: 'Image Missing Alt Attribute',
      wcagReference: 'WCAG 2.1 AA 1.1.1 Non-text Content',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Provide meaningful descriptive `alt` text for images, or `alt=""` if purely decorative.',
    },
    IMAGE_INVALID_ALT: {
      title: 'Image Has Placeholder or Filename Alt Text',
      wcagReference: 'WCAG 2.1 AA 1.1.1 Non-text Content',
      principle: 'Perceivable',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Replace placeholder alt text (e.g. "image", "photo.png") with meaningful descriptions.',
    },
    CONTRAST_FAILURE: {
      title: 'Insufficient Color Contrast Ratio',
      wcagReference: 'WCAG 2.1 AA 1.4.3 Contrast (Minimum)',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Ensure text contrast ratio meets at least 4.5:1 for normal text or 3:1 for large text against its background.',
    },
    TEXT_SCALING_FAILURE: {
      title: 'Layout Breaks on 200% Text Scaling',
      wcagReference: 'WCAG 2.1 AA 1.4.4 Resize Text',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Design responsive layouts that reflow without clipping or horizontal overflow when text is scaled to 200%.',
    },
    CONTENT_CLIPPED_ON_TEXT_SCALE: {
      title: 'Text Content Clipped on Text Scale',
      wcagReference: 'WCAG 2.1 AA 1.4.4 Resize Text',
      principle: 'Perceivable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Avoid fixed element heights and `overflow: hidden` on text containers.',
    },
    REDUCED_MOTION_FAILURE: {
      title: 'Non-Essential Motion Ignores prefers-reduced-motion',
      wcagReference: 'WCAG 2.1 AA 2.2.2 Pause, Stop, Hide',
      principle: 'Operable',
      defaultSeverity: 'low',
      defaultConfidence: 'medium',
      remediationHint: 'Disable or minimize looping animations when `prefers-reduced-motion: reduce` is active.',
    },
    TOUCH_TARGET_TOO_SMALL: {
      title: 'Mobile Touch Target Too Small',
      wcagReference: 'WCAG 2.2 AA 2.5.8 Target Size (Minimum)',
      principle: 'Operable',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Ensure interactive touch targets measure at least 24x24 CSS pixels with adequate spacing.',
    },
    DISABLED_STATE_INACCESSIBLE: {
      title: 'Disabled State Inaccessible to Screen Readers',
      wcagReference: 'WCAG 2.1 AA 4.1.2 Name, Role, Value',
      principle: 'Robust',
      defaultSeverity: 'low',
      defaultConfidence: 'high',
      remediationHint: 'Expose disabled state via native `disabled` attribute or `aria-disabled="true"`.',
    },
    LOADING_STATE_INACCESSIBLE: {
      title: 'Loading State Missing Accessible Indication',
      wcagReference: 'WCAG 2.1 AA 4.1.3 Status Messages',
      principle: 'Robust',
      defaultSeverity: 'low',
      defaultConfidence: 'medium',
      remediationHint: 'Add `aria-busy="true"` or accessible status announcement during async loading states.',
    },
    ACCESSIBILITY_REGRESSION: {
      title: 'Accessibility Regression Detected',
      wcagReference: 'WCAG 2.1 AA Automated Regression',
      principle: 'Robust',
      defaultSeverity: 'high',
      defaultConfidence: 'high',
      remediationHint: 'Investigate and resolve newly introduced accessibility defect compared to previous release baseline.',
    },
    ACCESSIBILITY_CHECK_INCONCLUSIVE: {
      title: 'Accessibility Check Inconclusive',
      wcagReference: 'Automated Observation',
      principle: 'Robust',
      defaultSeverity: 'info',
      defaultConfidence: 'low',
      remediationHint: 'Manually inspect this element or state where automated computed styles were indeterminate.',
    },
    ACCESSIBILITY_CONFIGURATION_ERROR: {
      title: 'Accessibility Engine Configuration Error',
      wcagReference: 'Internal Tooling',
      principle: 'Robust',
      defaultSeverity: 'info',
      defaultConfidence: 'high',
      remediationHint: 'Verify accessibility test configuration parameters and target URL validity.',
    },
  };

  public static getMetadata(type: AccessibilityFindingType): FindingMetadata {
    return this.METADATA_MAP[type] || {
      title: `Accessibility Finding: ${type}`,
      wcagReference: 'WCAG 2.1 AA Guidelines',
      principle: 'Robust',
      defaultSeverity: 'medium',
      defaultConfidence: 'high',
      remediationHint: 'Inspect and resolve accessibility defect following WCAG 2.1 guidelines.',
    };
  }
}

