// ==============================================================================
// Sculra Worker Role-Permission Matrix (worker/src/authz/role-permissions.ts)
// ==============================================================================

import { SculraRole } from './types';
import { PERMISSIONS, SculraPermission } from './permissions';

const BASE_VIEWER_PERMISSIONS: readonly SculraPermission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.MEMBERS_READ,
  PERMISSIONS.PROJECTS_READ,
  PERMISSIONS.SOURCES_READ,
  PERMISSIONS.CAMPAIGNS_READ,
  PERMISSIONS.TESTS_READ,
  PERMISSIONS.ISSUES_READ,
  PERMISSIONS.REPORTS_READ,
  PERMISSIONS.RELEASE_READ,
  PERMISSIONS.STRATEGY_READ,
  PERMISSIONS.SECURITY_READ,
  PERMISSIONS.PERFORMANCE_READ,
  PERMISSIONS.ACCESSIBILITY_READ,
  PERMISSIONS.CICD_READ,
  PERMISSIONS.REMEDIATION_READ,
  PERMISSIONS.FIX_AGENT_READ,
  PERMISSIONS.APPROVALS_READ,
  PERMISSIONS.OBSERVABILITY_READ,
  PERMISSIONS.INTEGRATIONS_READ,
  PERMISSIONS.SETTINGS_READ,
  PERMISSIONS.ENVIRONMENT_READ,
  PERMISSIONS.DEPLOYMENTS_READ,
  PERMISSIONS.RELEASES_READ,
  PERMISSIONS.CREDENTIALS_READ,
] as const;

const DEVELOPER_PERMISSIONS: readonly SculraPermission[] = [
  ...BASE_VIEWER_PERMISSIONS,
  PERMISSIONS.ISSUES_UPDATE,
  PERMISSIONS.ISSUES_RESOLVE,
  PERMISSIONS.REMEDIATION_REQUEST,
  PERMISSIONS.FIX_AGENT_PLAN,
  PERMISSIONS.DEPLOYMENTS_CREATE,
  PERMISSIONS.RELEASES_CREATE,
  PERMISSIONS.CREDENTIALS_USE,
] as const;

const QA_LEAD_PERMISSIONS: readonly SculraPermission[] = [
  ...DEVELOPER_PERMISSIONS,
  PERMISSIONS.PROJECTS_UPDATE,
  PERMISSIONS.SOURCES_CREATE,
  PERMISSIONS.SOURCES_UPDATE,
  PERMISSIONS.SOURCES_VALIDATE,
  PERMISSIONS.ENVIRONMENT_CREATE,
  PERMISSIONS.ENVIRONMENT_UPDATE,
  PERMISSIONS.CAMPAIGNS_CREATE,
  PERMISSIONS.CAMPAIGNS_START,
  PERMISSIONS.CAMPAIGNS_CANCEL,
  PERMISSIONS.CAMPAIGNS_CONFIGURE,
  PERMISSIONS.TESTS_RUN,
  PERMISSIONS.TESTS_CANCEL,
  PERMISSIONS.REPORTS_CREATE,
  PERMISSIONS.RELEASE_EVALUATE,
  PERMISSIONS.RELEASES_CHECK,
  PERMISSIONS.RELEASES_DECIDE,
  PERMISSIONS.CREDENTIALS_VALIDATE,
  PERMISSIONS.STRATEGY_CONFIGURE,
  PERMISSIONS.SECURITY_CONFIGURE,
  PERMISSIONS.SECURITY_RUN,
  PERMISSIONS.PERFORMANCE_CONFIGURE,
  PERMISSIONS.PERFORMANCE_RUN,
  PERMISSIONS.ACCESSIBILITY_CONFIGURE,
  PERMISSIONS.ACCESSIBILITY_RUN,
  PERMISSIONS.CICD_TRIGGER,
  PERMISSIONS.CICD_CONFIGURE,
  PERMISSIONS.REMEDIATION_APPLY,
  PERMISSIONS.FIX_AGENT_APPLY,
  PERMISSIONS.FIX_AGENT_CREATE_PR,
  PERMISSIONS.APPROVALS_APPROVE,
  PERMISSIONS.APPROVALS_REJECT,
  PERMISSIONS.OBSERVABILITY_ADMIN,
] as const;

const ADMIN_PERMISSIONS: readonly SculraPermission[] = [
  ...QA_LEAD_PERMISSIONS,
  PERMISSIONS.ORGANIZATION_UPDATE,
  PERMISSIONS.MEMBERS_INVITE,
  PERMISSIONS.MEMBERS_REMOVE,
  PERMISSIONS.MEMBERS_CHANGE_ROLE,
  PERMISSIONS.PROJECTS_CREATE,
  PERMISSIONS.PROJECTS_ARCHIVE,
  PERMISSIONS.PROJECTS_DELETE,
  PERMISSIONS.SOURCES_DELETE,
  PERMISSIONS.ENVIRONMENT_DELETE,
  PERMISSIONS.FIX_AGENT_CONFIGURE,
  PERMISSIONS.INTEGRATIONS_CONFIGURE,
  PERMISSIONS.SETTINGS_UPDATE,
  PERMISSIONS.CREDENTIALS_CREATE,
  PERMISSIONS.CREDENTIALS_UPDATE,
  PERMISSIONS.CREDENTIALS_DELETE,
  PERMISSIONS.CREDENTIALS_ROTATE,
] as const;

const OWNER_PERMISSIONS: readonly SculraPermission[] = [
  ...ADMIN_PERMISSIONS,
  PERMISSIONS.ORGANIZATION_DELETE,
  PERMISSIONS.MEMBERS_TRANSFER_OWNERSHIP,
] as const;

export const ROLE_PERMISSIONS: Record<SculraRole, ReadonlySet<SculraPermission>> = {
  OWNER: new Set(OWNER_PERMISSIONS),
  ADMIN: new Set(ADMIN_PERMISSIONS),
  QA_LEAD: new Set(QA_LEAD_PERMISSIONS),
  DEVELOPER: new Set(DEVELOPER_PERMISSIONS),
  VIEWER: new Set(BASE_VIEWER_PERMISSIONS),
};

export function hasPermission(role: SculraRole, permission: SculraPermission): boolean {
  const perms = ROLE_PERMISSIONS[role];
  return perms ? perms.has(permission) : false;
}
